import { LabourCosts } from "./models";

export const labourCosts: LabourCosts[] = [
  {
    providers: [
      {
        rebatesTotal: 0,
        grossPayTotal: 1173494.4,
        workerCount: 813,
        complianceStats: {
          OpsEmpStatusChecked: 499,
          Total: 82.86065636768888,
          TaxStatus: 91.08056265984655,
          Identification: 79.66751918158567,
          RightToWork: 79.66751918158567,
          OpsChecked: 3128,
          Contract: 83.43989769820972,
          EmpStatusReview: 67.73547094188376,
        },
        payrollAdminTotal: 0,
        labourCostTotal: 1173494.4,
        providerId: 1,
        name: "Senior Payroll Limited",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 18710.75,
        workerCount: 10,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 18710.75,
        providerId: 16,
        name: "Simple Pay Limited",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 10131.28,
        workerCount: 8,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 10131.28,
        providerId: 8,
        name: "Northern Contracting Limited",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 1753.04,
        workerCount: 7,
        complianceStats: {
          OpsEmpStatusChecked: 0,
          Total: 0,
          TaxStatus: 0,
          Identification: 0,
          RightToWork: 0,
          OpsChecked: 4,
          Contract: 25,
          EmpStatusReview: 0,
        },
        payrollAdminTotal: 0,
        labourCostTotal: 1753.04,
        providerId: 29,
        name: "Paddington Contracting Limited",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 9504.0,
        workerCount: 4,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 9504.0,
        providerId: 60,
        name: "Reliable Security Ltd",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 4409.36,
        workerCount: 4,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 4409.36,
        providerId: 65,
        name: "Hammer Pay Ltd",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 604.8,
        workerCount: 1,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 604.8,
        providerId: 5,
        name: "Canal Services Ltd",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 4013.5,
        workerCount: 1,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 4013.5,
        providerId: 7,
        name: "Personal Technology Limited",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 1586.0,
        workerCount: 1,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 1586.0,
        providerId: 11,
        name: "Construction Management Limited",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 2772.0,
        workerCount: 1,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 2772.0,
        providerId: 14,
        name: "CIS Payments Ltd",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 420.5,
        workerCount: 1,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 420.5,
        providerId: 20,
        name: "Worker Exchange Limited",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 1923.9,
        workerCount: 1,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 1923.9,
        providerId: 64,
        name: "Tradies Ltd",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 4500.0,
        workerCount: 1,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 4500.0,
        providerId: 67,
        name: "Paul's Building Services Ltd",
      },
      {
        rebatesTotal: 0,
        grossPayTotal: 8493.6,
        workerCount: 1,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 8493.6,
        providerId: 81,
        name: "The Agency Payroll Company Ltd",
      },
    ],
    directContractors: [
      {
        rebatesTotal: 0,
        grossPayTotal: 48157.66,
        workerCount: 13,
        complianceStats: null,
        payrollAdminTotal: 0,
        labourCostTotal: 48157.66,
        providerId: 0,
        name: "Direct Contractors",
      },
    ],
    total: [
      {
        rebatesTotal: 0,
        grossPayTotal: 1290474.79,
        workerCount: 867,
        complianceStats: {
          OpsEmpStatusChecked: 499,
          Total: 82.76656175635219,
          TaxStatus: 90.96424010217113,
          Identification: 79.56577266922095,
          RightToWork: 79.56577266922095,
          OpsChecked: 3132,
          Contract: 83.36526181353767,
          EmpStatusReview: 67.73547094188376,
        },
        payrollAdminTotal: 0,
        labourCostTotal: 1290474.79,
        providerId: 0,
        name: "Total",
      },
    ],
  },
];
